export const Project_data = [
  {
    project_name: "Car Rental Managment",
    src: "/project_img/car-mangament.jpg",
    href: "https://github.com/TheNinjan/car-rental-management-system",
    vhref:"#",
  },
  {
    project_name: "Smart Contacts",
    src: "/project_img/smart-contact.jpg",
    href: "https://github.com/TheNinjan/smart-contect-manager",
    vhref:"#"
  },
  {
    project_name:"Crypto-Statica",
    src:"/project_img/crypto.png",
    href:"https://github.com/TheNinjan/Crypto_statica",
    vhref:"https://crypto-statica.vercel.app/",
  },
  {
    project_name:"Fake PortFolio",
    src:"/project_img/fake.png",
    href:"https://github.com/TheNinjan/fake-portfolio",
    vhref:"https://personal-portfolio-dusky-two.vercel.app/",
  },
  {
    project_name:"The Video Hub",
    src:"/project_img/videohub.png",
    href:"https://github.com/TheNinjan/The_video_hub",
    vhref:"https://the-video-hub.vercel.app/",
  },
  {
    project_name:"Personal Portpholio",
    src:"/project_img/theninjan.png",
    href:"https://github.com/TheNinjan/personal-portfolio",
    vhref:"https://theninjan.vercel.app/",
  },
  {
    project_name:"NoteTaker",
    src:"/project_img/notetaker.png",
    href:"https://github.com/TheNinjan/note-taker",
    vhref:"https://note-taker-snowy.vercel.app/",
  },
  {
    project_name:"Ecommerce",
    src:"/project_img/ecommerce.png",
    href:"https://github.com/TheNinjan/ninja-mart",
    vhref:"#",
  },
  {
    project_name:"Prompt-Ninja",
    src:"/project_img/prompt.png",
    href:"https://github.com/TheNinjan/prompt-ninja",
    vhref:"https://prompt-ninja.vercel.app/",
  },
  {
    project_name:"Car-Show-Case",
    src:"/project_img/carshow.png",
    href:"https://github.com/TheNinjan/cars-show-case-nextjs",
    vhref:"https://cars-show-case-nextjs.vercel.app/",
  },
  {
    project_name:"Add to Cart",
    src:"/project_img/cart.png",
    href:"https://github.com/TheNinjan/Ecom_cart_with_Redux",
    vhref:"https://ecom-cart-with-redux.vercel.app/",
  },
  {
    project_name:"Taxi Go",
    src:"/project_img/taxi-go.png",
    href:"https://github.com/TheNinjan/taxi-go",
    vhref:"https://taxi-go.vercel.app/",
  },
  {
    project_name:"Shoping Cart",
    src:"/project_img/shoping-cart.png",
    href:"https://github.com/TheNinjan/shoping-cart",
    vhref:"https://shoping-cart-seven.vercel.app/",
  },
  {
    project_name:"TaskVista",
    src:"/project_img/taskvista.png",
    href:"https://github.com/TheNinjan/task-vista",
    vhref:"https://task-vista.vercel.app/",
  },
  {
    project_name:"Netflix Generes",
    src:"/project_img/netflix.png",
    href:"https://github.com/TheNinjan/netflix",
    vhref:"https://netflix-vert-chi.vercel.app/",
  },
  {
    project_name:"Amazon Clone",
    src:"/project_img/amazon.png",
    href:"https://github.com/TheNinjan/next_amazon_clone",
    vhref:"https://next-amazon-clone-delta.vercel.app/",
  },
  {
    project_name:"Flipkart",
    src:"/project_img/flipkart1.png",
    href:"https://github.com/TheNinjan/next-flipkart",
    vhref:"#",
  },
  {
    project_name:"EMI Calculator",
    src:"/project_img/emi.png",
    href:"https://github.com/TheNinjan/react-emi-calculator",
    vhref:"https://react-emi-calculator.vercel.app/",
  },
  {
    project_name:"Todos Application",
    src:"/project_img/todos.png",
    href:"https://github.com/TheNinjan/js-todos-app",
    vhref:"https://js-todos-app.vercel.app/",
  },
  {
    project_name:"Search Using HOC",
    src:"/project_img/search.png",
    href:"https://github.com/TheNinjan/reacr-search-functionality-HOC",
    vhref:"https://reacr-search-functionality-hoc.vercel.app/",
  },
  {
    project_name:"Calculator",
    src:"/project_img/cal.png",
    href:"https://github.com/TheNinjan/react-calculator",
    vhref:"https://react-calculator-delta-ochre.vercel.app/",
  },
  {
    project_name:"Myntra Clone",
    src:"/project_img/myntra.png",
    href:"https://github.com/TheNinjan/react-myntra-clone",
    vhref:"#",
  },
  {
    project_name:"Restro Landing Page",
    src:"/project_img/mxpert.png",
    href:"https://github.com/TheNinjan/task-mxpertz",
    vhref:"https://task-mxpertz.vercel.app/",
  },
  {
    project_name:"aneducare.com",
    src:"/project_img/an.png",
    href:"",
    vhref:"https://aneducare.com/",
  },
  {
    project_name:"grocji.com",
    src:"/project_img/grocji.png",
    href:"",
    vhref:"https://grocji.com/",
  },
  {
    project_name:"admin.grocji.com",
    src:"/project_img/grocji.png",
    href:"",
    vhref:"https://admin.grocji.com/",
  },
  {
    project_name:"DeepMind Hospital",
    src:"/project_img/hospital.png",
    href:"#",
    vhref:"#",
  },
  {
    project_name:"examhub.hashedbit.com",
    src:"/project_img/examhub.png",
    href:"",
    vhref:"https://examhub.hashedbit.com/",
  },
  {
    project_name:"learning.hashedbit.com",
    src:"/project_img/LMS.png",
    href:"",
    vhref:"https://learning.hashedbit.com/",
  },
  {
    project_name:"kanharajwadithal.in",
    src:"/project_img/krt.png",
    href:"",
    vhref:"https://kanharajwadithal.in/",
  },
  {
    project_name:"manishbansaldesigns.com",
    src:"/project_img/mb.png",
    href:"",
    vhref:"https://www.manishbansaldesigns.com/",
  },
  {
    project_name:"jscmsadmin.hashedbit.com",
    src:"/project_img/jscmsadmin.png",
    href:"",
    vhref:"https://jscmsadmin.hashedbit.com/blogslist",
  },
  {
    project_name:"hashedbit.com",
    src:"/project_img/hbi.png",
    href:"",
    vhref:"https://hashedbit.com/",
  },
  {
    project_name:"School Project",
    src:"/project_img/sp.png",
    href:"",
    vhref:"#",
  },
];
